// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9TLQNRgTn_TpcbPlAfIYHS9c6JjonZfg',
    appId: '1:898112614685:web:9808426b21a4da294cb1f4',
    messagingSenderId: '898112614685',
    projectId: 'hazel-strand-283910',
    authDomain: 'hazel-strand-283910.firebaseapp.com',
    storageBucket: 'hazel-strand-283910.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdCkwOrNic2BYWowQst1tBPncmin2RJXk',
    appId: '1:898112614685:android:41e9085be8bcc7ca4cb1f4',
    messagingSenderId: '898112614685',
    projectId: 'hazel-strand-283910',
    storageBucket: 'hazel-strand-283910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCxgRips1-XDHAVQsez1yH55SjQGgJadE',
    appId: '1:898112614685:ios:8a1658b0977fba524cb1f4',
    messagingSenderId: '898112614685',
    projectId: 'hazel-strand-283910',
    storageBucket: 'hazel-strand-283910.appspot.com',
    iosClientId: '898112614685-jh7dtikabd1rp5684f7stplstp6fq97o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginSignupFirebaseApp',
  );
}
